apiVersion: v1
kind: ConfigMap
metadata:
  name: customer-service-config
  namespace: default
data:
  config.yaml: |
    port: 8082
    sql:
      host: postgres.default.svc.cluster.local
      port: 5432
      username: postgres
      password: postgres
      name: postgres

